from color import Color, colorful_output

def help_documentation():
    colorful_output("MAX Calculator Help Documentation", Color.CYAN)
    print("Welcome to MAX Calculator Help Documentation!")
    print("Here are the available functionalities and their usage:")
    print()
    colorful_output("Basic Operations", Color.YELLOW)
    print("- Perform basic arithmetic operations such as addition, subtraction, multiplication, division, etc.")
    print("- Access the Basic Operations menu from the main menu.")
    print()
    colorful_output("Expression Evaluation", Color.YELLOW)
    print("- Evaluate mathematical expressions involving multiple operations and parentheses.")
    print("- Choose the Expression Evaluation option from the main menu.")
    print()
    colorful_output("Unit Conversion", Color.YELLOW)
    print("- Convert between different units of measurement such as length, mass, and volume.")
    print("- Access the Unit Conversion menu from the main menu.")
    print()
    colorful_output("Variable Storage", Color.YELLOW)
    print("- Store and retrieve variables for reuse in calculations.")
    print("- Utilize the Variable Storage feature from the main menu.")
    print()
    colorful_output("Command History", Color.YELLOW)
    print("- Keep track of previous calculations and review them when needed.")
    print("- Navigate to the Command History option from the main menu.")
    print()
    colorful_output("File Management", Color.YELLOW)
    print("- Save and load calculation history to/from files.")
    print("- Manage files using the File Management option from the main menu.")
    print()
    colorful_output("Help Documentation", Color.YELLOW)
    print("- Get assistance and information about the calculator's functionalities.")
    print("- View the Help Documentation option from the main menu.")
    print()
    colorful_output("Quit", Color.YELLOW)
    print("- Exit the calculator application.")
    print("- Choose the Quit option from the main menu.")
    print()
    colorful_output("Enjoy using MAX Calculator!", Color.GREEN)
    # press any key to continue
    input("Press any key to continue...")
    return
